const ImporterActionTypes = {
	UPDATE_CHANNEL_SNIPPET: 'UPDATE_CHANNEL_SNIPPET',
	UPDATE_PLAYLIST_SNIPPET: 'UPDATE_PLAYLIST_SNIPPET',
	UPDATE_VIDEO_SNIPPET: 'UPDATE_VIDEO_SNIPPET',
	UPDATE_IMPORTER_CONFIG: 'UPDATE_IMPORTER_CONFIG'
}

export default ImporterActionTypes